@startuml
title 基于GitHub的实验管理平台--评定成绩用例的顺序图
actor teachers
== 查看成绩 ==
teachers -> students : 输入学号
students -> grades
grades -> tests
tests --> teachers:每个实验的信息、成绩和评语
== 评定成绩 ==
teachers -> grades : 录入并提交每个实验的成绩
@enduml