@startuml
title 基于GitHub的实验管理平台--用例图
actor teachers
actor students
actor users
users <|-- teachers
users <|-- students

package 用户用例集 {
users --up-> (登录)
users --up-> (登出)
users --up-> (查看用户信息)
users --up-> (修改用户信息)
users --up-> (修改密码)
}
package 业务用例集 {
teachers ---> (评定成绩)
teachers ---> (学生列表)
students ---> (学生列表)
students ---> (查看成绩)
}

@enduml