@startuml

企业基础表 : <b>企业ID
企业基础表 : 企业名称
企业基础表 : 地址
企业基础表 : 邮编
企业基础表 : 联系人
企业基础表 : 联系电话
企业基础表 : 人数
企业基础表 : <I>城市代码
企业基础表 : <I><B>生产状况
企业基础表 : 生产设备开机率
企业基础表 : 生产线类型
企业基础表 : 生产线数量
企业基础表 : <I><B>经济类型
企业基础表 : 产量_上一年
企业基础表 : 销售额_上一年
企业基础表 : <I><B>科研投入
企业基础表 : 生产许可证有效期_开始
企业基础表 : 生产许可证有效期_终止
企业基础表 : <I><B>质量管理办法
企业基础表 : 检验人员人数
企业基础表 : 检验人员有证书的人数
企业基础表 : <I><B>质量提升需求
企业基础表 : <I><B>主要原材料品种
企业基础表 : <I><B>原材料主要来源
企业基础表 : <I><B>原材料质量把关
企业基础表 : <I><B>出厂检验_方式
企业基础表 : <I><B>出厂检验_成品检验人员
企业基础表 : <I><B>出厂检验_主要检测设备状态
企业基础表 : <I><B>出厂检验_检验原始记录
企业基础表 : <I><B>抽查产品执行标准
企业基础表 : 产品供货标准
企业基础表 : 遇到的困难
note left: <B>通用语言：\n选择字段类型定义

用户表 : <b>用户名
用户表 : 密码
用户表 : 用户类型
用户表 : 企业ID
用户表 : 城市代码
用户表 : 单位名称
用户表 : 联系人
用户表 : 联系地址
用户表 : 联系电话
用户表 : 备注
用户表 : 申请日期
用户表 : 审批日期
用户表 : 启用


站内消息表 : <b>消息ID
站内消息表 : 接收企业ID
站内消息表 : 消息标题
站内消息表 : 消息内容
站内消息表 : 发送时间
站内消息表 : 阅读时间

分析报告共享表 : <b>文件ID
分析报告共享表 : 接收企业ID
分析报告共享表 : 上传时间
分析报告共享表 : 报告名称
分析报告共享表 : 文件名称

检验项目基础表 : <b>检验项目ID
检验项目基础表 : 项目名称
检验项目基础表 : 子项目名称
检验项目基础表 : 计量单位

产品类型表 : <b>产品类型编号
产品类型表 : 产品名称
产品类型表 : 规格型号

产品类型_检验项目表 : <b>产品类型编号
产品类型_检验项目表 : <b>检验项目ID
产品类型_检验项目表 : 序号
产品类型_检验项目表 : 技术要求
产品类型_检验项目表 : 误差限量
产品类型_检验项目表 : 误差算法
产品类型_检验项目表 : 误差限量说明
note left: <B>通用语言：\n误差限量语法定义\n及满意度自动计算方法

检验报告表 : <b>报告编号
检验报告表 : 产品类型编号
检验报告表 : 生产日期
检验报告表 : 批号
检验报告表 : 商标
检验报告表 : 送样人
检验报告表 : 样品数量
检验报告表 : 企业ID
检验报告表 : 企业检验日期
检验报告表 : 检测机构检验日期
检验报告表 : 检验依据
检验报告表 : 进度

检验报告单项表 : <b>报告编号
检验报告单项表 : <b>检验项目ID
检验报告单项表 : 企业检验录入
检验报告单项表 : 企业检验结果
检验报告单项表 : 企业单项评定
检验报告单项表 : 检测机构检验录入
检验报告单项表 : 检测机构检验结果
检验报告单项表 : 检测机构单项评定
检验报告单项表 : 不同实验室间误差
检验报告单项表 : 满意度
note left: <B>通用语言：\n录入信息转换为结果信息\n误差限量语法定义及满意度自动计算方法

城市代码表 : <b>代码
城市代码表 : 城市
城市代码表 : 省

检验报告表 "1" --{ "m" 检验报告单项表:包含
产品类型表 "1" --{ "m" 产品类型_检验项目表:包含

企业基础表 "1" -right-{ "m" 检验报告表:包含
企业基础表  -down-> 城市代码表 : 依赖
检验报告单项表 -up-> 检验项目基础表 : 依赖
检验报告单项表 -up-> 产品类型_检验项目表 : 依赖


站内消息表 -up-> 企业基础表 : 依赖
用户表 -up-> 企业基础表 : 依赖
分析报告共享表 -up-> 企业基础表 : 依赖

检验项目基础表 "1" -left-{ "m" 产品类型_检验项目表:包含
@enduml