@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
Title 时序图

actor 企业
database 系统平台
actor 检测机构
actor 监管机构
actor 系统管理员
== 初始化 ==
企业->系统平台:用户注册
检测机构->系统平台:用户注册
监管机构->系统平台:用户注册
系统管理员->系统平台:用户审批
系统管理员->系统平台:用户停用
系统管理员->系统平台:用户启用
系统管理员->系统平台:密码重置
检测机构 -> 系统平台:基础数据管理
企业->系统平台:企业基础表管理
== 日常主要工作流程 ==
企业->系统平台:新建检验报告
企业->系统平台:检验信息录入
企业->系统平台:提交检验报告
... 企业向检测部门提供检验样品，线下完成 ...
检测机构->系统平台:检验信息录入
note right:可以通过快速录入检验信息接口录入检验信息\n可以发出消息：误差超出允许范围提醒
检测机构->系统平台:完成检验报告
检测机构->系统平台:统计报表导出
企业->系统平台:检验报告查询
检测机构->系统平台:检验报告查询
监管机构->系统平台:检验报告查询
note right:发出消息：生产企业产品质量发生偏离趋势提醒
== 其他工作 ==
检测机构->系统平台:分析报告上传
企业->系统平台:分析报告下载
系统平台->企业:定时发送消息：送检水泥对比样品提醒
@enduml