@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
title 用例图
left to right direction
actor 检测机构
actor 系统管理员
actor 企业
actor 监管机构
interface "快速录入检验信息接口" as Interface1
package 基础数据管理 {
检测机构 -up- (检验项目基础表管理)
检测机构 -up- (产品类型表管理)
检测机构 -up- (产品类型_检验项目表管理)
}
package 用户管理 {
企业 -up- (用户注册)
系统管理员 -up- (用户审批)
系统管理员 -up- (用户查询)
系统管理员 -up- (用户停用)
系统管理员 -up- (用户启用)
企业 -up- (修改密码)
检测机构 -up- (修改密码)
监管机构 -up- (修改密码)
系统管理员 -up- (密码重置)
企业 -up- (企业基础表管理)
企业 -up- (企业基础表查询)
检测机构 -up- (企业基础表查询)
}
package 检验报告管理 {
企业 -down- (新建检验报告)
企业 -down- (删除检验报告)
企业 -down- (修改检验报告)
检测机构 -down- (修改检验报告)
企业 -down- (提交检验报告)
检测机构 -down- (完成检验报告)
企业 -down- (检验信息录入)
检测机构 -down- (检验信息录入)
检测机构 -down- (消息发送：误差超出允许范围提醒)
企业 -down- (检验报告查询)
检测机构 -down- (检验报告查询)
监管机构 -down- (检验报告查询)
}
Interface1 ..|>(检验信息录入) : 报告系统数据

package 统计报表导出 {
检测机构 -up- (单个检验项目所有企业的数据统计和图表)
检测机构 -up- (单个检验项目企业历次数据统计和图表)
检测机构 -up- (消息发送：生产企业产品质量发生偏离趋势提醒)
检测机构 -up- (全省水泥产品类别和规格型号统计图表)
检测机构 -up- (企业所在地统计图表)
检测机构 -up- (全省平均值统计)

监管机构 -up- (单个检验项目所有企业的数据统计和图表)
监管机构 -up- (单个检验项目企业历次数据统计和图表)
监管机构 -up- (全省水泥产品类别和规格型号统计图表)
监管机构 -up- (企业所在地统计图表)
监管机构 -up- (全省平均值统计)
}

package 消息提醒 {
检测机构 -down- (消息发送：送检水泥对比样品提醒)
检测机构 -down- (消息查询)
企业 -down- (消息查询)
企业 -down- (消息标记为已读)
}
package 分析报告共享 {
检测机构 -down- (分析报告上传)
检测机构 -down- (分析报告查询)
检测机构 -down- (分析报告删除)
检测机构 -down- (分析报告下载)
企业 -down- (分析报告查询)
监管机构 -down- (分析报告查询)
企业 -down- (分析报告下载)
监管机构 -down- (分析报告下载)
}
@enduml