@startuml
title 新建检验报告工作流程
start
:<b>企业用户登录平台;
:<b>输入或者选择:
报告编号
产品类型编号（选择）
生产日期
批号
商标
送样人
样品数量
检验依据;
:<b>点击“创建新检验报告”;
if (选择的“产品类型编号”是否存在于“产品类型_检验项目表”中？)then(存在)
:<b>新建一行检验报告表记录（父表）:
系统自动生成一条用户记录,
申请日期=当天日期,但是审批日期为空，不能登录;

:系统创建一份新的检验报告，系统自动设置该检验报告的：
企业检验日期=空, 检测机构检验日期=空，进度=空
企业ID=该用户的企业ID;
:<b>新建多行检验报告单项表记录（子表）:
系统自动根据“产品类型_检验项目表”中的产品类型编号的所有检验项目，
新增相同数目的“检验报告单项表”记录。把基础表“产品类型_检验项目表”中的检验项目ID按序复制到新增记录中。
这样，新增的“检验报告单项表”记录只有“报告编号”和“检验项目ID”两个字段有值。
其余字段如“企业检验录入,企业单项评定,检测机构检验录入,检测机构单项评定”就等待企业或者检测机构录入。;
:提示创建成功;
else(不存在)
:<b>终止新建检验报告:
提示必须预先配置该“产品类型编号”的检验项目;
endif
stop
@enduml