@startuml
title 检验信息-企业录入及提交流程\n本流程描述企业录入检验信息到最后提交的过程
start
:<b>企业用户登录平台;
:进入检验报告查询页面;
:查询企业自已的未提交的检验报告<b>（父表）:
即检验报告表的“进度”为空;
:选择一个未提交的检验报告;
fork
:点击“检验信息录入”按钮;
:进入检验报告单项表的修改界面<b>（子表）;
:修改各单项值的两个属性：
1：输入“企业检验录入”值，系统自动计算出“企业检验结果”值，
   方法是“通用语言：录入信息转换为结果信息”
2：选择“企业单项评定”为“合格”或者“不合格”;
fork
:点击“保存”按钮
保存各单项值的修改;
fork again
:点击“返回”按钮
结束录入;
end fork
fork again
:点击“提交”按钮;
:系统自动设置:
“企业检验日期”=当时日期
<b>“进度”=“已提交”;
end fork
stop
@enduml