@startuml
title 检验信息-检测机构录入及完成流程\n本流程描述检测机构录入检验信息到最后完成检验的过程
start
:<b>检测机构用户登录平台;
:进入检验报告查询页面;
:查询所有企业的已提交的但未完成的检验报告<b>（父表）:
即检验报告表的“进度”=“已提交”;
:选择一个已提交的检验报告;
fork
:点击“检验信息录入”按钮;
:进入检验报告单项表的修改界面<b>（子表）;
:修改各单项值的两个属性：
1：输入“检测机构检验录入”值，系统自动计算出“检测机构检验结果”值，
   方法是“通用语言：录入信息转换为结果信息”
2：选择“检测机构单项评定”为“合格”或者“不合格”;
:自动计算:“不同实验室间误差”,“满意度”
方法是：“通用语言：误差限量语法定义及满意度自动计算方法”;
fork
:点击“保存”按钮
保存各单项值的修改;
fork again
:发出消息：
误差超出允许范围提醒;
fork again
:点击“返回”按钮
不保存修改，结束录入;
end fork
fork again
:<b>点击“从接口自动录入”按钮
这是检验信息的自动录入
根据接口程序自动从报告系统数据库的中
将这个检验报告的各个单项数据复制过来
而不需要手工录入。;
fork again
:点击“完成检验”按钮;
:系统自动设置:
“检测机构检验日期”=当时日期
<b>“进度”=“已完成”;
end fork
stop
@enduml