@startuml
title 自动计算检验报告单项表的“不同实验室间误差”和“满意度”
start
:输入4项:\na=企业检验结果\nb=检测机构检验结果\n误差算法\n误差限量;
if (误差算法) then (绝对误差)
:不同实验室间误差=round(a-b,2);
elseif (误差算法) then (相对误差)
if (a+b=0?) then (是)
:不同实验室间误差=空;
else(否)
:不同实验室间误差=round((a-b)*2/(a+b),2);
endif
else(空)
:不同实验室间误差=空;
endif
:c=不同实验室间误差;
if (c) then (为空)
:满意度=空;
elseif(误差限量) then (为空)
:满意度=空;
elseif(b和c根据通用语言2定义的算法是否满足“误差限量”？) then (满足)
:满意度=“满意”;
else(不满足)
:满意度=“不满意”;
endif
stop
@enduml