@startuml
title 用户账号注册及审批流程
start
:<b>访客进入平台;
:<b>访客输入:
用户名，密码(两次确认)
单位名称，联系人，联系地址，联系电话
备注(可选)
<b>选择：
用户类型：企业/检测机构/监管机构 3选1
城市代码：根据城市代码表;
if (用户名是否重复?)then(不重复)
:注册成功:
系统自动生成一条用户记录,
申请日期=当天日期,但是审批日期为空，不能登录;
else(重复)
:注册失败:
不生成用户记录;
endif
:<b>系统管理员登录平台;
:查询未审批的一个用户
(用户表中审批日期为空的记录);
if (手工判断该用户是否合理?) then(合理)
    if (用户类型是否为企业？)then(企业)
    if (“单位名称”是否已经存在于“企业基础表”中?) then(存在)
    :从“企业基础表”中取出这个企业的“企业ID”
    并将获取的“企业ID”值置入用户表中的“企业ID”字段;
    else(不存在)
    :系统自动创建一条“企业基础表”记录，
    利用用户表中的：单位名称，联系人，联系地址，联系电话和城市代码
    生成一个新企业，得到一个新的“企业ID”值
    并将这个新的“企业ID”值置入用户表中的“企业ID”字段;
    endif
    else(非企业)
    endif
    :系统自动设置：审批日期=当天日期
    <b>用户可以登录了;
else(不合理)
endif
stop
@enduml