@startuml
start
:录单;
:提交订单;
:<b>订单表</b>\n订单状态=2\n<b>订单详表</b>\n半油半免=空\n是否需要部件分解=空;
note left
订单表
   订单状态=2
   五金下单方式=空
   五金包含=0
   门板线归尺统计=空
   条码=空
  五金计划完成日期，五金实际完成日期
end note
note right
    五金下单方式的定义：
    为空表示五金未下单，
        取值为“订单”表示五金按单个订单汇总下单，
        取值为“组单”表示五金按组单汇总下单，
        其他值表示多订单合并下单产生的五金下单批次号
    五金包含的定义：
    0表示无五金，1或者3表示有门窗，2或者3表示有家具。
    如果五金下单方式是批次号，则表示整个批次号，否则表示一个订单
end note
:订单审核;
note left
TT_订单审核
   TT_重新编号
   TT_订单审核_门板线规尺 （按订单归尺）
   TT_五金下单
end note
if (订单是"非生产单":[S_订单是非生产订单](@OrderID)=1?) then (yes)
    :<b>订单表</b>\n订单状态=6;
    #HotPink:<b>订单表_五金下单表</b>\n生成按组合并的门窗五金;
else (no)
    :<b>订单表</b>\n订单状态=4\n<b>订单详表</b>\n半油半免=计算值\n是否需要部件分解=计算值;
    note right
        五金下单方式=NULL
        五金包含=0
        门板线归尺统计=计算值
        条码=计算值
    end note
    :<b>订单详表_数量详单表</b>;
    note right
        订单详表_数量详单表
        不需要分解的详单生成数量详单记录，但是：
             不包括详单中的门板线
             不包括生产厂 为('外购','其它')的小类产品。
        包括新产生的归尺后的门板线
    end note
    if (有家具?) then (yes)
        :TopSolid拆分家具;
        note left
            TT_Insert_After订单详表_组件部件表
            TT_五金下单_重新按组单方式汇总
        end note
        :<b>订单详表_组件部件表</b>;
        #HotPink:<b>订单表_五金下单表</b>\n生成按组合并的家具五金;
    else(No)
    endif
    :生产下单;
    :<b>订单表</b>\n订单状态=5;
    :<b>订单表_门窗生产流程表</b>\n<b>订单表_门窗生产流程表_组单表</b>;
    note right:用于生产反馈
    :生产反馈;
    :<b>订单表</b>\n订单状态=6;
    note right
    6:白胚完成
    油漆完成:油漆检验完成日期不为空
    end note
endif
:包装;
:<b>订单表</b>\n订单状态=7;
note right :已生产完成;
:发货;
:<b>订单表</b>\n订单状态=8;
note right :已发货完成;
stop
@enduml